namespace com.sisware.gui.form
{
    partial class CategoryForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CategoryForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            this.label5 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.buttonSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonClean = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TexboxName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelDate = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.buttonNewSubCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.textBoxSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buttonNew = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridViewCategory = new Guna.UI2.WinForms.Guna2DataGridView();
            this.ss_patientTableAdapter1 = new SISWARE.DataSet2TableAdapters.ss_patientTableAdapter();
            this.ColumIdCategory = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ColumNameCategory = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ColumDateCategory = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewCategory)).BeginInit();
            this.SuspendLayout();
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(514, 28);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(51, 20);
            this.label5.TabIndex = 26;
            this.label5.Text = "Buscar:";
            // 
            // groupBox1
            // 
            this.groupBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(220)))), ((int)(((byte)(228)))));
            this.groupBox1.Controls.Add(this.buttonSave);
            this.groupBox1.Controls.Add(this.buttonClean);
            this.groupBox1.Controls.Add(this.TexboxName);
            this.groupBox1.Controls.Add(this.labelDate);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Enabled = false;
            this.groupBox1.Location = new System.Drawing.Point(23, 506);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(4);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(4);
            this.groupBox1.Size = new System.Drawing.Size(810, 140);
            this.groupBox1.TabIndex = 23;
            this.groupBox1.TabStop = false;
            this.groupBox1.Visible = false;
            this.groupBox1.Enter += new System.EventHandler(this.groupBox1_Enter);
            // 
            // buttonSave
            // 
            this.buttonSave.AllowAnimations = true;
            this.buttonSave.AllowMouseEffects = true;
            this.buttonSave.AllowToggling = false;
            this.buttonSave.AnimationSpeed = 200;
            this.buttonSave.AutoGenerateColors = false;
            this.buttonSave.AutoRoundBorders = false;
            this.buttonSave.AutoSizeLeftIcon = true;
            this.buttonSave.AutoSizeRightIcon = true;
            this.buttonSave.BackColor = System.Drawing.Color.Transparent;
            this.buttonSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.buttonSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonSave.BackgroundImage")));
            this.buttonSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.ButtonText = "Guardar";
            this.buttonSave.ButtonTextMarginLeft = 0;
            this.buttonSave.ColorContrastOnClick = 45;
            this.buttonSave.ColorContrastOnHover = 45;
            this.buttonSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonSave.CustomizableEdges = borderEdges1;
            this.buttonSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonSave.DisabledFillColor = System.Drawing.Color.Empty;
            this.buttonSave.DisabledForecolor = System.Drawing.Color.Empty;
            this.buttonSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonSave.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonSave.ForeColor = System.Drawing.Color.White;
            this.buttonSave.IconLeft = global::SISWARE.Properties.Resources.save;
            this.buttonSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonSave.IconMarginLeft = 11;
            this.buttonSave.IconPadding = 10;
            this.buttonSave.IconRight = null;
            this.buttonSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonSave.IconSize = 25;
            this.buttonSave.IdleBorderColor = System.Drawing.Color.Empty;
            this.buttonSave.IdleBorderRadius = 0;
            this.buttonSave.IdleBorderThickness = 0;
            this.buttonSave.IdleFillColor = System.Drawing.Color.Empty;
            this.buttonSave.IdleIconLeftImage = global::SISWARE.Properties.Resources.save;
            this.buttonSave.IdleIconRightImage = null;
            this.buttonSave.IndicateFocus = false;
            this.buttonSave.Location = new System.Drawing.Point(21, 87);
            this.buttonSave.Name = "buttonSave";
            this.buttonSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonSave.OnDisabledState.BorderRadius = 1;
            this.buttonSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.OnDisabledState.BorderThickness = 1;
            this.buttonSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonSave.OnDisabledState.IconLeftImage = null;
            this.buttonSave.OnDisabledState.IconRightImage = null;
            this.buttonSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonSave.onHoverState.BorderRadius = 1;
            this.buttonSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.onHoverState.BorderThickness = 1;
            this.buttonSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(229)))), ((int)(((byte)(234)))));
            this.buttonSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonSave.onHoverState.IconLeftImage = null;
            this.buttonSave.onHoverState.IconRightImage = null;
            this.buttonSave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonSave.OnIdleState.BorderRadius = 1;
            this.buttonSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.OnIdleState.BorderThickness = 1;
            this.buttonSave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(157)))), ((int)(((byte)(184)))));
            this.buttonSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonSave.OnIdleState.IconLeftImage = global::SISWARE.Properties.Resources.save;
            this.buttonSave.OnIdleState.IconRightImage = null;
            this.buttonSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonSave.OnPressedState.BorderRadius = 1;
            this.buttonSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.OnPressedState.BorderThickness = 1;
            this.buttonSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonSave.OnPressedState.IconLeftImage = null;
            this.buttonSave.OnPressedState.IconRightImage = null;
            this.buttonSave.Size = new System.Drawing.Size(120, 38);
            this.buttonSave.TabIndex = 34;
            this.buttonSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonSave.TextMarginLeft = 0;
            this.buttonSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonSave.UseDefaultRadiusAndThickness = true;
            this.buttonSave.Click += new System.EventHandler(this.buttonSave_Click);
            // 
            // buttonClean
            // 
            this.buttonClean.AllowAnimations = true;
            this.buttonClean.AllowMouseEffects = true;
            this.buttonClean.AllowToggling = false;
            this.buttonClean.AnimationSpeed = 200;
            this.buttonClean.AutoGenerateColors = false;
            this.buttonClean.AutoRoundBorders = false;
            this.buttonClean.AutoSizeLeftIcon = true;
            this.buttonClean.AutoSizeRightIcon = true;
            this.buttonClean.BackColor = System.Drawing.Color.Transparent;
            this.buttonClean.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.buttonClean.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonClean.BackgroundImage")));
            this.buttonClean.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClean.ButtonText = "Limpiar";
            this.buttonClean.ButtonTextMarginLeft = 0;
            this.buttonClean.ColorContrastOnClick = 45;
            this.buttonClean.ColorContrastOnHover = 45;
            this.buttonClean.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonClean.CustomizableEdges = borderEdges2;
            this.buttonClean.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonClean.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClean.DisabledFillColor = System.Drawing.Color.Empty;
            this.buttonClean.DisabledForecolor = System.Drawing.Color.Empty;
            this.buttonClean.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonClean.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonClean.ForeColor = System.Drawing.Color.White;
            this.buttonClean.IconLeft = global::SISWARE.Properties.Resources.eraser;
            this.buttonClean.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonClean.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClean.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonClean.IconMarginLeft = 11;
            this.buttonClean.IconPadding = 10;
            this.buttonClean.IconRight = null;
            this.buttonClean.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonClean.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClean.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonClean.IconSize = 25;
            this.buttonClean.IdleBorderColor = System.Drawing.Color.Empty;
            this.buttonClean.IdleBorderRadius = 0;
            this.buttonClean.IdleBorderThickness = 0;
            this.buttonClean.IdleFillColor = System.Drawing.Color.Empty;
            this.buttonClean.IdleIconLeftImage = global::SISWARE.Properties.Resources.eraser;
            this.buttonClean.IdleIconRightImage = null;
            this.buttonClean.IndicateFocus = false;
            this.buttonClean.Location = new System.Drawing.Point(147, 87);
            this.buttonClean.Name = "buttonClean";
            this.buttonClean.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClean.OnDisabledState.BorderRadius = 1;
            this.buttonClean.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClean.OnDisabledState.BorderThickness = 1;
            this.buttonClean.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClean.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClean.OnDisabledState.IconLeftImage = null;
            this.buttonClean.OnDisabledState.IconRightImage = null;
            this.buttonClean.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonClean.onHoverState.BorderRadius = 1;
            this.buttonClean.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClean.onHoverState.BorderThickness = 1;
            this.buttonClean.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(229)))), ((int)(((byte)(234)))));
            this.buttonClean.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonClean.onHoverState.IconLeftImage = null;
            this.buttonClean.onHoverState.IconRightImage = null;
            this.buttonClean.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonClean.OnIdleState.BorderRadius = 1;
            this.buttonClean.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClean.OnIdleState.BorderThickness = 1;
            this.buttonClean.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(157)))), ((int)(((byte)(184)))));
            this.buttonClean.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonClean.OnIdleState.IconLeftImage = global::SISWARE.Properties.Resources.eraser;
            this.buttonClean.OnIdleState.IconRightImage = null;
            this.buttonClean.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonClean.OnPressedState.BorderRadius = 1;
            this.buttonClean.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClean.OnPressedState.BorderThickness = 1;
            this.buttonClean.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonClean.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonClean.OnPressedState.IconLeftImage = null;
            this.buttonClean.OnPressedState.IconRightImage = null;
            this.buttonClean.Size = new System.Drawing.Size(120, 38);
            this.buttonClean.TabIndex = 33;
            this.buttonClean.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonClean.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonClean.TextMarginLeft = 0;
            this.buttonClean.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonClean.UseDefaultRadiusAndThickness = true;
            this.buttonClean.Click += new System.EventHandler(this.buttonClean_Click);
            // 
            // TexboxName
            // 
            this.TexboxName.AcceptsReturn = false;
            this.TexboxName.AcceptsTab = false;
            this.TexboxName.AnimationSpeed = 200;
            this.TexboxName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TexboxName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TexboxName.AutoSizeHeight = true;
            this.TexboxName.BackColor = System.Drawing.Color.Transparent;
            this.TexboxName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TexboxName.BackgroundImage")));
            this.TexboxName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TexboxName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TexboxName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TexboxName.BorderColorIdle = System.Drawing.Color.Silver;
            this.TexboxName.BorderRadius = 10;
            this.TexboxName.BorderThickness = 1;
            this.TexboxName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TexboxName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TexboxName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TexboxName.DefaultText = "";
            this.TexboxName.FillColor = System.Drawing.Color.White;
            this.TexboxName.HideSelection = true;
            this.TexboxName.IconLeft = null;
            this.TexboxName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TexboxName.IconPadding = 10;
            this.TexboxName.IconRight = null;
            this.TexboxName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TexboxName.Lines = new string[0];
            this.TexboxName.Location = new System.Drawing.Point(21, 50);
            this.TexboxName.MaxLength = 32767;
            this.TexboxName.MinimumSize = new System.Drawing.Size(1, 1);
            this.TexboxName.Modified = false;
            this.TexboxName.Multiline = false;
            this.TexboxName.Name = "TexboxName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TexboxName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TexboxName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TexboxName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TexboxName.OnIdleState = stateProperties4;
            this.TexboxName.Padding = new System.Windows.Forms.Padding(3);
            this.TexboxName.PasswordChar = '\0';
            this.TexboxName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TexboxName.PlaceholderText = "Nombre de la Categoria";
            this.TexboxName.ReadOnly = false;
            this.TexboxName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TexboxName.SelectedText = "";
            this.TexboxName.SelectionLength = 0;
            this.TexboxName.SelectionStart = 0;
            this.TexboxName.ShortcutsEnabled = true;
            this.TexboxName.Size = new System.Drawing.Size(557, 31);
            this.TexboxName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TexboxName.TabIndex = 22;
            this.TexboxName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TexboxName.TextMarginBottom = 0;
            this.TexboxName.TextMarginLeft = 3;
            this.TexboxName.TextMarginTop = 1;
            this.TexboxName.TextPlaceholder = "Nombre de la Categoria";
            this.TexboxName.UseSystemPasswordChar = false;
            this.TexboxName.WordWrap = true;
            // 
            // labelDate
            // 
            this.labelDate.AutoSize = true;
            this.labelDate.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelDate.Location = new System.Drawing.Point(607, 50);
            this.labelDate.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelDate.Name = "labelDate";
            this.labelDate.Size = new System.Drawing.Size(29, 20);
            this.labelDate.TabIndex = 15;
            this.labelDate.Text = "[...]";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(607, 25);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(46, 20);
            this.label4.TabIndex = 3;
            this.label4.Text = "Fecha:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(17, 25);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(56, 20);
            this.label3.TabIndex = 2;
            this.label3.Text = "Nombre:";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(21, 34);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(115, 20);
            this.label1.TabIndex = 15;
            this.label1.Text = "Lista de Categorías";
            // 
            // buttonNewSubCategory
            // 
            this.buttonNewSubCategory.AllowAnimations = true;
            this.buttonNewSubCategory.AllowMouseEffects = true;
            this.buttonNewSubCategory.AllowToggling = false;
            this.buttonNewSubCategory.AnimationSpeed = 200;
            this.buttonNewSubCategory.AutoGenerateColors = false;
            this.buttonNewSubCategory.AutoRoundBorders = false;
            this.buttonNewSubCategory.AutoSizeLeftIcon = true;
            this.buttonNewSubCategory.AutoSizeRightIcon = true;
            this.buttonNewSubCategory.BackColor = System.Drawing.Color.Transparent;
            this.buttonNewSubCategory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.buttonNewSubCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonNewSubCategory.BackgroundImage")));
            this.buttonNewSubCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNewSubCategory.ButtonText = "Nueva SubCategoria";
            this.buttonNewSubCategory.ButtonTextMarginLeft = 0;
            this.buttonNewSubCategory.ColorContrastOnClick = 45;
            this.buttonNewSubCategory.ColorContrastOnHover = 45;
            this.buttonNewSubCategory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.buttonNewSubCategory.CustomizableEdges = borderEdges3;
            this.buttonNewSubCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonNewSubCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonNewSubCategory.DisabledFillColor = System.Drawing.Color.Empty;
            this.buttonNewSubCategory.DisabledForecolor = System.Drawing.Color.Empty;
            this.buttonNewSubCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonNewSubCategory.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonNewSubCategory.ForeColor = System.Drawing.Color.White;
            this.buttonNewSubCategory.IconLeft = global::SISWARE.Properties.Resources.newfile;
            this.buttonNewSubCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonNewSubCategory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonNewSubCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonNewSubCategory.IconMarginLeft = 11;
            this.buttonNewSubCategory.IconPadding = 10;
            this.buttonNewSubCategory.IconRight = null;
            this.buttonNewSubCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonNewSubCategory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonNewSubCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonNewSubCategory.IconSize = 25;
            this.buttonNewSubCategory.IdleBorderColor = System.Drawing.Color.Empty;
            this.buttonNewSubCategory.IdleBorderRadius = 0;
            this.buttonNewSubCategory.IdleBorderThickness = 0;
            this.buttonNewSubCategory.IdleFillColor = System.Drawing.Color.Empty;
            this.buttonNewSubCategory.IdleIconLeftImage = global::SISWARE.Properties.Resources.newfile;
            this.buttonNewSubCategory.IdleIconRightImage = null;
            this.buttonNewSubCategory.IndicateFocus = false;
            this.buttonNewSubCategory.Location = new System.Drawing.Point(610, 460);
            this.buttonNewSubCategory.Name = "buttonNewSubCategory";
            this.buttonNewSubCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonNewSubCategory.OnDisabledState.BorderRadius = 1;
            this.buttonNewSubCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNewSubCategory.OnDisabledState.BorderThickness = 1;
            this.buttonNewSubCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonNewSubCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonNewSubCategory.OnDisabledState.IconLeftImage = null;
            this.buttonNewSubCategory.OnDisabledState.IconRightImage = null;
            this.buttonNewSubCategory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonNewSubCategory.onHoverState.BorderRadius = 1;
            this.buttonNewSubCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNewSubCategory.onHoverState.BorderThickness = 1;
            this.buttonNewSubCategory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(229)))), ((int)(((byte)(234)))));
            this.buttonNewSubCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonNewSubCategory.onHoverState.IconLeftImage = null;
            this.buttonNewSubCategory.onHoverState.IconRightImage = null;
            this.buttonNewSubCategory.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonNewSubCategory.OnIdleState.BorderRadius = 1;
            this.buttonNewSubCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNewSubCategory.OnIdleState.BorderThickness = 1;
            this.buttonNewSubCategory.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(157)))), ((int)(((byte)(184)))));
            this.buttonNewSubCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonNewSubCategory.OnIdleState.IconLeftImage = global::SISWARE.Properties.Resources.newfile;
            this.buttonNewSubCategory.OnIdleState.IconRightImage = null;
            this.buttonNewSubCategory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonNewSubCategory.OnPressedState.BorderRadius = 1;
            this.buttonNewSubCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNewSubCategory.OnPressedState.BorderThickness = 1;
            this.buttonNewSubCategory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonNewSubCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonNewSubCategory.OnPressedState.IconLeftImage = null;
            this.buttonNewSubCategory.OnPressedState.IconRightImage = null;
            this.buttonNewSubCategory.Size = new System.Drawing.Size(223, 38);
            this.buttonNewSubCategory.TabIndex = 32;
            this.buttonNewSubCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonNewSubCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonNewSubCategory.TextMarginLeft = 0;
            this.buttonNewSubCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonNewSubCategory.UseDefaultRadiusAndThickness = true;
            this.buttonNewSubCategory.Click += new System.EventHandler(this.buttonNewSubCategory_Click);
            // 
            // buttonDelete
            // 
            this.buttonDelete.AllowAnimations = true;
            this.buttonDelete.AllowMouseEffects = true;
            this.buttonDelete.AllowToggling = false;
            this.buttonDelete.AnimationSpeed = 200;
            this.buttonDelete.AutoGenerateColors = false;
            this.buttonDelete.AutoRoundBorders = false;
            this.buttonDelete.AutoSizeLeftIcon = true;
            this.buttonDelete.AutoSizeRightIcon = true;
            this.buttonDelete.BackColor = System.Drawing.Color.Transparent;
            this.buttonDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.buttonDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonDelete.BackgroundImage")));
            this.buttonDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonDelete.ButtonText = "Eliminar";
            this.buttonDelete.ButtonTextMarginLeft = 0;
            this.buttonDelete.ColorContrastOnClick = 45;
            this.buttonDelete.ColorContrastOnHover = 45;
            this.buttonDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.buttonDelete.CustomizableEdges = borderEdges4;
            this.buttonDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonDelete.DisabledFillColor = System.Drawing.Color.Empty;
            this.buttonDelete.DisabledForecolor = System.Drawing.Color.Empty;
            this.buttonDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonDelete.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonDelete.ForeColor = System.Drawing.Color.White;
            this.buttonDelete.IconLeft = global::SISWARE.Properties.Resources.delete;
            this.buttonDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonDelete.IconMarginLeft = 11;
            this.buttonDelete.IconPadding = 10;
            this.buttonDelete.IconRight = null;
            this.buttonDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonDelete.IconSize = 25;
            this.buttonDelete.IdleBorderColor = System.Drawing.Color.Empty;
            this.buttonDelete.IdleBorderRadius = 0;
            this.buttonDelete.IdleBorderThickness = 0;
            this.buttonDelete.IdleFillColor = System.Drawing.Color.Empty;
            this.buttonDelete.IdleIconLeftImage = global::SISWARE.Properties.Resources.delete;
            this.buttonDelete.IdleIconRightImage = null;
            this.buttonDelete.IndicateFocus = false;
            this.buttonDelete.Location = new System.Drawing.Point(276, 461);
            this.buttonDelete.Name = "buttonDelete";
            this.buttonDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonDelete.OnDisabledState.BorderRadius = 1;
            this.buttonDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonDelete.OnDisabledState.BorderThickness = 1;
            this.buttonDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonDelete.OnDisabledState.IconLeftImage = null;
            this.buttonDelete.OnDisabledState.IconRightImage = null;
            this.buttonDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonDelete.onHoverState.BorderRadius = 1;
            this.buttonDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonDelete.onHoverState.BorderThickness = 1;
            this.buttonDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(229)))), ((int)(((byte)(234)))));
            this.buttonDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonDelete.onHoverState.IconLeftImage = null;
            this.buttonDelete.onHoverState.IconRightImage = null;
            this.buttonDelete.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonDelete.OnIdleState.BorderRadius = 1;
            this.buttonDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonDelete.OnIdleState.BorderThickness = 1;
            this.buttonDelete.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(157)))), ((int)(((byte)(184)))));
            this.buttonDelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonDelete.OnIdleState.IconLeftImage = global::SISWARE.Properties.Resources.delete;
            this.buttonDelete.OnIdleState.IconRightImage = null;
            this.buttonDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonDelete.OnPressedState.BorderRadius = 1;
            this.buttonDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonDelete.OnPressedState.BorderThickness = 1;
            this.buttonDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonDelete.OnPressedState.IconLeftImage = null;
            this.buttonDelete.OnPressedState.IconRightImage = null;
            this.buttonDelete.Size = new System.Drawing.Size(120, 38);
            this.buttonDelete.TabIndex = 31;
            this.buttonDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonDelete.TextMarginLeft = 0;
            this.buttonDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonDelete.UseDefaultRadiusAndThickness = true;
            this.buttonDelete.Click += new System.EventHandler(this.buttonDelete_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Editar";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges5;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = global::SISWARE.Properties.Resources.file_edit;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = global::SISWARE.Properties.Resources.file_edit;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(150, 461);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(229)))), ((int)(((byte)(234)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(157)))), ((int)(((byte)(184)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = global::SISWARE.Properties.Resources.file_edit;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(120, 38);
            this.bunifuButton1.TabIndex = 30;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // textBoxSearch
            // 
            this.textBoxSearch.AcceptsReturn = false;
            this.textBoxSearch.AcceptsTab = false;
            this.textBoxSearch.AnimationSpeed = 200;
            this.textBoxSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxSearch.AutoSizeHeight = true;
            this.textBoxSearch.BackColor = System.Drawing.Color.Transparent;
            this.textBoxSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxSearch.BackgroundImage")));
            this.textBoxSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxSearch.BorderRadius = 10;
            this.textBoxSearch.BorderThickness = 1;
            this.textBoxSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textBoxSearch.DefaultText = "";
            this.textBoxSearch.FillColor = System.Drawing.Color.White;
            this.textBoxSearch.HideSelection = true;
            this.textBoxSearch.IconLeft = null;
            this.textBoxSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxSearch.IconPadding = 10;
            this.textBoxSearch.IconRight = null;
            this.textBoxSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxSearch.Lines = new string[0];
            this.textBoxSearch.Location = new System.Drawing.Point(574, 19);
            this.textBoxSearch.MaxLength = 32767;
            this.textBoxSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxSearch.Modified = false;
            this.textBoxSearch.Multiline = false;
            this.textBoxSearch.Name = "textBoxSearch";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxSearch.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxSearch.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxSearch.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxSearch.OnIdleState = stateProperties8;
            this.textBoxSearch.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxSearch.PasswordChar = '\0';
            this.textBoxSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textBoxSearch.PlaceholderText = "Buscar por nombre";
            this.textBoxSearch.ReadOnly = false;
            this.textBoxSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxSearch.SelectedText = "";
            this.textBoxSearch.SelectionLength = 0;
            this.textBoxSearch.SelectionStart = 0;
            this.textBoxSearch.ShortcutsEnabled = true;
            this.textBoxSearch.Size = new System.Drawing.Size(260, 32);
            this.textBoxSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textBoxSearch.TabIndex = 28;
            this.textBoxSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxSearch.TextMarginBottom = 0;
            this.textBoxSearch.TextMarginLeft = 3;
            this.textBoxSearch.TextMarginTop = 1;
            this.textBoxSearch.TextPlaceholder = "Buscar por nombre";
            this.textBoxSearch.UseSystemPasswordChar = false;
            this.textBoxSearch.WordWrap = true;
            this.textBoxSearch.KeyUp += new System.Windows.Forms.KeyEventHandler(this.bunifuTextBox1_KeyUp);
            // 
            // buttonNew
            // 
            this.buttonNew.AllowAnimations = true;
            this.buttonNew.AllowMouseEffects = true;
            this.buttonNew.AllowToggling = false;
            this.buttonNew.AnimationSpeed = 200;
            this.buttonNew.AutoGenerateColors = false;
            this.buttonNew.AutoRoundBorders = false;
            this.buttonNew.AutoSizeLeftIcon = true;
            this.buttonNew.AutoSizeRightIcon = true;
            this.buttonNew.BackColor = System.Drawing.Color.Transparent;
            this.buttonNew.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.buttonNew.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonNew.BackgroundImage")));
            this.buttonNew.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNew.ButtonText = "Nuevo";
            this.buttonNew.ButtonTextMarginLeft = 0;
            this.buttonNew.ColorContrastOnClick = 45;
            this.buttonNew.ColorContrastOnHover = 45;
            this.buttonNew.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.buttonNew.CustomizableEdges = borderEdges6;
            this.buttonNew.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonNew.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonNew.DisabledFillColor = System.Drawing.Color.Empty;
            this.buttonNew.DisabledForecolor = System.Drawing.Color.Empty;
            this.buttonNew.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonNew.Font = new System.Drawing.Font("Franklin Gothic Medium Cond", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonNew.ForeColor = System.Drawing.Color.White;
            this.buttonNew.IconLeft = global::SISWARE.Properties.Resources._new;
            this.buttonNew.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonNew.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonNew.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonNew.IconMarginLeft = 11;
            this.buttonNew.IconPadding = 10;
            this.buttonNew.IconRight = null;
            this.buttonNew.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonNew.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonNew.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonNew.IconSize = 25;
            this.buttonNew.IdleBorderColor = System.Drawing.Color.Empty;
            this.buttonNew.IdleBorderRadius = 0;
            this.buttonNew.IdleBorderThickness = 0;
            this.buttonNew.IdleFillColor = System.Drawing.Color.Empty;
            this.buttonNew.IdleIconLeftImage = global::SISWARE.Properties.Resources._new;
            this.buttonNew.IdleIconRightImage = null;
            this.buttonNew.IndicateFocus = false;
            this.buttonNew.Location = new System.Drawing.Point(24, 460);
            this.buttonNew.Name = "buttonNew";
            this.buttonNew.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonNew.OnDisabledState.BorderRadius = 1;
            this.buttonNew.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNew.OnDisabledState.BorderThickness = 1;
            this.buttonNew.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonNew.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonNew.OnDisabledState.IconLeftImage = null;
            this.buttonNew.OnDisabledState.IconRightImage = null;
            this.buttonNew.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(111)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.buttonNew.onHoverState.BorderRadius = 1;
            this.buttonNew.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNew.onHoverState.BorderThickness = 1;
            this.buttonNew.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(229)))), ((int)(((byte)(234)))));
            this.buttonNew.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonNew.onHoverState.IconLeftImage = null;
            this.buttonNew.onHoverState.IconRightImage = null;
            this.buttonNew.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.buttonNew.OnIdleState.BorderRadius = 1;
            this.buttonNew.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNew.OnIdleState.BorderThickness = 1;
            this.buttonNew.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(157)))), ((int)(((byte)(184)))));
            this.buttonNew.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonNew.OnIdleState.IconLeftImage = global::SISWARE.Properties.Resources._new;
            this.buttonNew.OnIdleState.IconRightImage = null;
            this.buttonNew.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonNew.OnPressedState.BorderRadius = 1;
            this.buttonNew.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonNew.OnPressedState.BorderThickness = 1;
            this.buttonNew.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(121)))), ((int)(((byte)(180)))));
            this.buttonNew.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonNew.OnPressedState.IconLeftImage = null;
            this.buttonNew.OnPressedState.IconRightImage = null;
            this.buttonNew.Size = new System.Drawing.Size(120, 38);
            this.buttonNew.TabIndex = 29;
            this.buttonNew.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonNew.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonNew.TextMarginLeft = 0;
            this.buttonNew.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonNew.UseDefaultRadiusAndThickness = true;
            this.buttonNew.Click += new System.EventHandler(this.buttonNew_Click);
            // 
            // dataGridViewCategory
            // 
            this.dataGridViewCategory.AllowUserToAddRows = false;
            this.dataGridViewCategory.AllowUserToResizeColumns = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.dataGridViewCategory.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridViewCategory.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridViewCategory.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.dataGridViewCategory.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridViewCategory.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridViewCategory.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI", 8F);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.DimGray;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridViewCategory.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridViewCategory.ColumnHeadersHeight = 40;
            this.dataGridViewCategory.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.ColumIdCategory,
            this.ColumNameCategory,
            this.ColumDateCategory});
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridViewCategory.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridViewCategory.EnableHeadersVisualStyles = false;
            this.dataGridViewCategory.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.dataGridViewCategory.Location = new System.Drawing.Point(23, 58);
            this.dataGridViewCategory.Margin = new System.Windows.Forms.Padding(4);
            this.dataGridViewCategory.Name = "dataGridViewCategory";
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridViewCategory.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dataGridViewCategory.RowHeadersVisible = false;
            this.dataGridViewCategory.RowHeadersWidth = 51;
            this.dataGridViewCategory.RowTemplate.DividerHeight = 5;
            this.dataGridViewCategory.RowTemplate.Height = 40;
            this.dataGridViewCategory.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewCategory.Size = new System.Drawing.Size(811, 395);
            this.dataGridViewCategory.TabIndex = 33;
            this.dataGridViewCategory.Theme = Guna.UI2.WinForms.Enums.DataGridViewPresetThemes.Default;
            this.dataGridViewCategory.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridViewCategory.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.dataGridViewCategory.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.dataGridViewCategory.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.dataGridViewCategory.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.dataGridViewCategory.ThemeStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.dataGridViewCategory.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.dataGridViewCategory.ThemeStyle.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.dataGridViewCategory.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.dataGridViewCategory.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.dataGridViewCategory.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.DimGray;
            this.dataGridViewCategory.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
            this.dataGridViewCategory.ThemeStyle.HeaderStyle.Height = 40;
            this.dataGridViewCategory.ThemeStyle.ReadOnly = false;
            this.dataGridViewCategory.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridViewCategory.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridViewCategory.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.dataGridViewCategory.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.dataGridViewCategory.ThemeStyle.RowsStyle.Height = 40;
            this.dataGridViewCategory.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.dataGridViewCategory.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            // 
            // ss_patientTableAdapter1
            // 
            this.ss_patientTableAdapter1.ClearBeforeFill = true;
            // 
            // ColumIdCategory
            // 
            this.ColumIdCategory.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.ColumIdCategory.FillWeight = 40.60914F;
            this.ColumIdCategory.HeaderText = "ID";
            this.ColumIdCategory.MinimumWidth = 6;
            this.ColumIdCategory.Name = "ColumIdCategory";
            this.ColumIdCategory.Visible = false;
            this.ColumIdCategory.Width = 10;
            // 
            // ColumNameCategory
            // 
            this.ColumNameCategory.FillWeight = 99.49239F;
            this.ColumNameCategory.HeaderText = "Nombre";
            this.ColumNameCategory.MinimumWidth = 6;
            this.ColumNameCategory.Name = "ColumNameCategory";
            // 
            // ColumDateCategory
            // 
            this.ColumDateCategory.FillWeight = 99.49239F;
            this.ColumDateCategory.HeaderText = "Fecha";
            this.ColumDateCategory.MinimumWidth = 6;
            this.ColumDateCategory.Name = "ColumDateCategory";
            // 
            // CategoryForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.ClientSize = new System.Drawing.Size(846, 652);
            this.Controls.Add(this.dataGridViewCategory);
            this.Controls.Add(this.buttonNewSubCategory);
            this.Controls.Add(this.buttonDelete);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.textBoxSearch);
            this.Controls.Add(this.buttonNew);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "CategoryForm";
            this.Text = "Category";
            this.Load += new System.EventHandler(this.CategoryForm_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewCategory)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label labelDate;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonNew;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonNewSubCategory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonSave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonClean;
        private Bunifu.UI.WinForms.BunifuTextBox TexboxName;
        private Guna.UI2.WinForms.Guna2DataGridView dataGridViewCategory;
        private SISWARE.DataSet2TableAdapters.ss_patientTableAdapter ss_patientTableAdapter1;
        private System.Windows.Forms.DataGridViewTextBoxColumn ColumIdCategory;
        private System.Windows.Forms.DataGridViewTextBoxColumn ColumNameCategory;
        private System.Windows.Forms.DataGridViewTextBoxColumn ColumDateCategory;
    }
}